### ISSUE TITLE
Your API Keys are exposed

### ISSUE THREAD

**Issue by email362** [jeff-k-zhou/NoToxicBot#1]
Anyone that opens your repo can see your API keys in your commit history. I would suggest either: getting new api keys and deleting the exposed ones, or hard reseting your git commit history so that the .env file isnt in your git log. Cool bot though! Cheers! 🥂

**Comment by jeff-k-zhou** [comment]
Yeah I forgot to gitignore the .env on accident. Don't worry, I regenerated the keys shortly after. Thanks for letting me know!
